services:
    Netgen\Bundle\IbexaAdminUIExtraBundle\Controller\Content\UpdateAlwaysAvailable:
        parent: Ibexa\Contracts\AdminUi\Controller\Controller
        arguments:
            - '@translator'
            - '@ibexa.api.service.content'
            - '@Netgen\Bundle\IbexaAdminUIExtraBundle\Form\FormFactory'
            - '@Ibexa\Core\Helper\TranslationHelper'
