netgen.ibexa_admin_ui_extra.content.update_always_available:
    path: /content/{id}/update-always-available
    methods: ['POST']
    controller: 'Netgen\Bundle\IbexaAdminUIExtraBundle\Controller\Content\UpdateAlwaysAvailable'
    requirements:
        id: \d+
